openapi: 3.0.0
info:
  title: API Six Cities
  version: 1.0.0

paths:
  /offers:
    get:
      tags:
        - Offers
      summary: Get a list of offers
      description: Retrieve a list of offers.
      parameters:
        - name: count
          in: query
          description: Count offers
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferLiteRDO'

    post:
      tags:
        - Offers
      summary: Create a new offer
      description: Create a new offer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferDTO'
      responses:
        201:
          description: Offer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        422:
          description: Unprocessable Entity
        401:
          description: Unauthorized

  /offers/{offerId}:
    parameters:
      - name: offerId
        in: path
        required: true
        description: The ID of the offer to manipulate
        schema:
          type: string
    get:
      tags:
        - Offers
      summary: Get an offer by ID
      description: Retrieve an offer by its unique ID.
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        404:
          description: Offer not found
        422:
          description: Unprocessable Entity

    put:
      tags:
        - Offers
      summary: Update an offer by ID
      description: Update an offer by its unique ID. Allow user who create offer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferDTO'
      responses:
        200:
          description: Offer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        401:
          description: Unauthorized
        404:
          description: Offer not found
        422:
          description: Unprocessable Entity
        403:
          description: Forbidden

    delete:
      tags:
        - Offers
      summary: Delete an offer by ID
      description: Delete an offer by its unique ID. Allow user who create offer.
      responses:
        204:
          description: Offer deleted successfully
        404:
          description: Offer not found
        403:
          description: Forbidden
        422:
          description: Unprocessable Entity

  /offers/{offerId}/comments:
    get:
      tags:
        - Comments
      summary: Get comments for an offer
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to retrieve comments.
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentOut'
        404:
          description: Offer not found
        422:
          description: Unprocessable Entity

    post:
      tags:
        - Comments
      summary: Create a new comment for an offer. Allow user who create offer.
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to create a comment
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentOut'
      responses:
        201:
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentOut'
        422:
          description: Unprocessable Entity
        401:
          description: Unauthorized

  /offers/premium/{city}:
    get:
      tags:
        - Premium offers
      summary: Get premium offers
      description: Premium list offers
      parameters:
        - name: city
          in: path
          required: true
          description: City for filter premium offers
          schema:
            type: string
      responses:
        200:
          description: Successfully get premium offers

  /offers/{offerId}/favorites:
    post:
      tags:
        - Favourites offers
      summary: Add an offer to favorites
      description: Add an offer to the user's list of favorites.
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to add to favorites
          schema:
            type: string
      responses:
        201:
          description: Offer added to favorites successfully
        404:
          description: Offer not found
        401:
          description: Unauthorized
        422:
          description: Unprocessable Entity

    delete:
      tags:
        - Favourites offers
      summary: Remove an offer from favorites
      description: Remove an offer from the user's list of favorites.
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to remove from favorites
          schema:
            type: string
      responses:
        204:
          description: Offer removed from favorites successfully
        404:
          description: Offer not found
        401:
          description: Unauthorized
        422:
          description: Unprocessable Entity

  /offers/favorites:
    get:
      tags:
        - Favourites offers
      summary: Get user favourites offers
      responses:
        200:
          description: Successful get favourites offers
        401:
          description: Unauthorized

  /offers/{offerId}/preview-image:
    post:
      tags:
        - Offers files
      summary: Upload preview image
      responses:
        201:
          description: Preview image successful upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageRDO'
        401:
          description: User not auth
        403:
          description: User not access to object
        422:
          description: Validation error

  /offers/{offerId}/image:
    post:
      tags:
        - Offers files
      summary: Upload image
      responses:
        204:
          description: Image successful upload
        401:
          description: User not auth
        403:
          description: User not access to object
        422:
          description: Validation error

    delete:
      tags:
        - Offers files
      summary: Delete image
      responses:
        204:
          description: Image successful delete
        401:
          description: User not auth
        403:
          description: User not access to object
        422:
          description: Validation error

  /users/sign-up:
    post:
      tags:
        - Users
      summary: User sign up
      description: Sign up new user
      requestBody:
        description: User information for create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "201":
          description: User successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRDO'
        "409":
          description: User with same email exists

  /users/sign-in:
    post:
      tags:
        - Users
      summary: Sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: User sign in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInUserRDO'
        422:
          description: Validation error

  /users/sign-out:
    post:
      tags:
        - Users
      summary: Sign out the current user
      responses:
        204:
          description: User logged out successfully
        401:
          description: Unauthorized

  /users/{userId}/avatar:
    post:
      tags:
        - Users
      summary: Upload avatar
      responses:
        201:
          description: Avatar upload successfuly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvatarRDO'
        422:
          description: Unprocessable Entity


tags:
  - name: Offers
    description: Endpoints related to offers.

  - name: Comments
    description: Endpoints related to comments on offers.

  - name: Users
    description: Endpoints related to user management, login, and registration.

  - name: Favourites
    description: Endpoints related to managing favorite offers.

components:
  schemas:
    ImageRDO:
      type: object
      properties:
        image:
          type: string

    UserType:
      type: string
      enum:
        - standart
        - pro

    CityEnum:
      type: string
      enum:
        - Paris
        - Cologne
        - Brussels
        - Amsterdam
        - Hamburg
        - Dusseldorf

    HouseType:
      type: string
      enum:
        - apartment
        - house
        - room
        - hotel

    Facilities:
      type: string
      enum:
        - Breakfast
        - Air conditioning
        - Laptop friendly workspace
        - Baby seat
        - Washer
        - Towels
        - Fridge

    Coordinates:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      required:
        - latitude
        - longitude

    UserRDO:
      type: object
      properties:
        id:
          type: number
        username:
          type: string
        email:
          type: string
        avatar:
          type: string
        type:
          $ref: "#/components/schemas/UserType"

    UserDTO:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        type:
          $ref: "#/components/schemas/UserType"
        password:
          type: string
    
    SignInUserRDO:
      type: object
      properties:
        token:
          type: string
        email:
          type: string

    AvatarRDO:
      type: object
      properties:
        avatar: 
          type: string

    OfferDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        isPremium:
          type: boolean
        previewImage:
          type: string
        houseType:
          $ref: '#/components/schemas/HouseType'
        roomCount:
          type: number
        guestCount:
          type: number
        cost:
          type: number
        facilities:
          type: array
          items:
            $ref: '#/components/schemas/Facilities'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
      required:
        - name
        - description
        - city
        - previewImage
        - isPremium
        - houseType
        - roomCount
        - guestCount
        - cost
        - facilities
        - coordinates

    OfferRDO:
      type: object
      properties:
        id:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
            example: [https://mybacket/offer.jpg]
          minItems: 6
          maxItems: 6
        name:
          type: string
        description:
          type: string
        publicationDate:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        houseType:
          $ref: '#/components/schemas/HouseType'
        roomCount:
          type: number
        guestCount:
          type: number
        cost:
          type: number
        facilities:
          type: array
          items:
            $ref: '#/components/schemas/Facilities'
        author:
          $ref: '#/components/schemas/UserRDO'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        commentsCount:
          type: number

    OfferLiteRDO:
      type: object
      properties:
        id:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        previewImage:
          type: string
        name:
          type: string
        description:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        houseType:
          $ref: '#/components/schemas/HouseType'
        cost:
          type: number
        commentsCount:
          type: number

    CommentOut:
      type: object
      properties:
        id:
          type: number
        user:
          $ref: '#/components/schemas/UserRDO'
        rating:
          type: number
        comment:
          type: string
        date:
          type: string
          format: date-time

    CommentIn:
      type: object
      properties:
        comment:
          type: string
        rating:
          type: number

      required:
        - comment
        - rating
