openapi: 3.0.0
info:
  title: API Six Cities
  version: 1.0.0

paths:
  /offers:
    get:
      tags:
        - Offers
      summary: Get a list of offers
      description: Retrieve a list of offers.
      parameters:
        - name: count
          in: query
          description: Count offers
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferLiteRDO'

    post:
      tags:
        - Offers
      summary: Create a new offer
      description: Create a new offer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferDTO'
      responses:
        201:
          description: Offer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        422:
          description: Unprocessable Entity
        401:
          description: Unauthorized

  /offers/{offerId}:
    parameters:
      - name: offerId
        in: path
        required: true
        description: The ID of the offer to manipulate
        schema:
          type: string
    get:
      tags:
        - Offers
      summary: Get an offer by ID
      description: Retrieve an offer by its unique ID.
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        404:
          description: Offer not found
        403:
          description: Forbidden

    put:
      tags:
        - Offers
      summary: Update an offer by ID
      description: Update an offer by its unique ID. Allow user who create offer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferDTO'
      responses:
        200:
          description: Offer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferRDO'
        404:
          description: Offer not found
        422:
          description: Unprocessable Entity
        403:
          description: Forbidden

    delete:
      tags:
        - Offers
      summary: Delete an offer by ID
      description: Delete an offer by its unique ID. Allow user who create offer.
      responses:
        204:
          description: Offer deleted successfully
        404:
          description: Offer not found
        400:
          description: Bad request

  /offers/{offerId}/comments:
    get:
      tags:
        - Comments
      summary: Get comments for an offer
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to retrieve comments for
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of comments to return (optional)
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The number of comments to skip (optional)
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentOut'
        404:
          description: Offer not found
        401:
          description: Unauthorized

    post:
      tags:
        - Comments
      summary: Create a new comment for an offer
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to create a comment for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentOut'
      responses:
        201:
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentOut'
        422:
          description: Unprocessable Entity
        401:
          description: Unauthorized

  /offers/{offerId}/favorites:
    post:
      tags:
        - Favourites
      summary: Add an offer to favorites
      description: Add an offer to the user's list of favorites.
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to add to favorites
          schema:
            type: string
      responses:
        201:
          description: Offer added to favorites successfully
        404:
          description: Offer not found
        401:
          description: Unauthorized

    delete:
      tags:
        - Favourites
      summary: Remove an offer from favorites
      description: Remove an offer from the user's list of favorites.
      parameters:
        - name: offerId
          in: path
          required: true
          description: The ID of the offer to remove from favorites
          schema:
            type: string
      responses:
        204:
          description: Offer removed from favorites successfully
        404:
          description: Offer not found
        401:
          description: Unauthorized

  /user:
    get:
      tags:
        - User
      summary: Get the current user
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOut'
        401:
          description: Unauthorized

  /user/login:
    post:
      tags:
        - User
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOut'
        422:
          description: Unprocessable Entity

  /user/logout:
    post:
      tags:
        - User
      summary: Logout the current user
      responses:
        204:
          description: User logged out successfully
        401:
          description: Unauthorized

  /user/register:
    post:
      tags:
        - User
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                avatar:
                  type: string
                password:
                  type: string
                type:
                  $ref: '#/components/schemas/UserType'
              required:
                - name
                - email
                - password
                - type
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOut'
        422:
          description: Unprocessable Entity


tags:
  - name: Offers
    description: Endpoints related to offers.

  - name: Comments
    description: Endpoints related to comments on offers.

  - name: Users
    description: Endpoints related to user management, login, and registration.

  - name: Favourites
    description: Endpoints related to managing favorite offers.

components:
  schemas:
    UserType:
      type: string
      enum:
        - standart
        - pro

    CityEnum:
      type: string
      enum:
        - Paris
        - Cologne
        - Brussels
        - Amsterdam
        - Hamburg
        - Dusseldorf

    HouseType:
      type: string
      enum:
        - apartment
        - house
        - room
        - hotel

    Facilities:
      type: string
      enum:
        - Breakfast
        - Air conditioning
        - Laptop friendly workspace
        - Baby seat
        - Washer
        - Towels
        - Fridge

    Coordinates:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      required:
        - latitude
        - longitude

    UserOut:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
        isPro:
          type: boolean
        token: string

    UserOfferRDO:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        isPro:
          type: boolean
        avatarUrl:
          type: string

    OfferDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        isPremium:
          type: boolean
        previewImage:
          type: string
        houseType:
          $ref: '#/components/schemas/HouseType'
        roomCount:
          type: number
        guestCount:
          type: number
        cost:
          type: number
        facilities:
          type: array
          items:
            $ref: '#/components/schemas/Facilities'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
      required:
        - name
        - description
        - city
        - previewImage
        - isPremium
        - houseType
        - roomCount
        - guestCount
        - cost
        - facilities
        - coordinates

    OfferRDO:
      type: object
      properties:
        id:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
            example: [https://mybacket/offer.jpg]
          minItems: 6
          maxItems: 6
        name:
          type: string
        description:
          type: string
        publicationDate:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        houseType:
          $ref: '#/components/schemas/HouseType'
        roomCount:
          type: number
        guestCount:
          type: number
        cost:
          type: number
        facilities:
          type: array
          items:
            $ref: '#/components/schemas/Facilities'
        author:
          $ref: '#/components/schemas/UserOfferRDO'
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        commentsCount:
          type: number

    OfferLiteRDO:
      type: object
      properties:
        id:
          type: string
        city:
          $ref: '#/components/schemas/CityEnum'
        previewImage:
          type: string
        name:
          type: string
        description:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
        houseType:
          $ref: '#/components/schemas/HouseType'
        cost:
          type: number
        commentsCount:
          type: number

    CommentOut:
      type: object
      properties:
        id:
          type: number
        user:
          $ref: '#/components/schemas/UserOfferRDO'
        rating:
          type: number
        comment:
          type: string
        date:
          type: string
          format: date-time

    CommentIn:
      type: object
      properties:
        comment:
          type: string
        rating:
          type: number

      required:
        - comment
        - rating
